# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WoodcutCli < Formula
  desc "A simple description of your application."
  homepage "https://github.com/zeepk/woodcut-cli"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zeepk/woodcut-cli/releases/download/v0.1.4/woodcut-cli_0.1.4_Darwin_arm64.tar.gz"
      sha256 "b843bb294c46445203a1668d8a8cda1810f7854302b757f6d67926fa47448885"

      def install
        bin.install "woodcut"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zeepk/woodcut-cli/releases/download/v0.1.4/woodcut-cli_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "87c29e8cb1a2c67c19e39cc183afbf0c03ee35037d30e0e2ce5fb79cf32cd36d"

      def install
        bin.install "woodcut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zeepk/woodcut-cli/releases/download/v0.1.4/woodcut-cli_0.1.4_Linux_x86_64.tar.gz"
      sha256 "02ca2307effbe15b650cb69440aa6cbea742275a535ec593176cfd2fe6deaf3a"

      def install
        bin.install "woodcut"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zeepk/woodcut-cli/releases/download/v0.1.4/woodcut-cli_0.1.4_Linux_arm64.tar.gz"
      sha256 "815d0c8a478ee9dcc8015d458ad7a6e76b6c1724f902e2c1fe750d54261926a8"

      def install
        bin.install "woodcut"
      end
    end
  end
end
